name: Push Container to Docker Hub

on:
    push:
        branches:
            - main
        paths-ignore:
            - 'README.md'
            - 'infrastructure.bicep'
            - '.github/*'

jobs:
    push-to-dockerhub:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/azure-function-convert-email-to-pdf:latest
